### PR TITLE
Bump CONTROLLER_TOOLS_VERSION to 0.14.0

### PR DESCRIPTION
**Pull request by stuggi**
bump controller tools to the version which bumps k8s deps to v0.29.0, which aligns with the version in the operators.

### CODE REVIEW

**Comment by stuggi** [comment]
@fmount there is an issue with the glance crd which prevents bumping to controller tools 0.14.0. The `imageCache.size` is a required value. With controller-tools 0.14.0 support for empty maps/lists was introduced https://github.com/kubernetes-sigs/controller-tools/releases/tag/v0.14.0 . This now really applies the defaulting in [1] . Is the imageCache config a required config for glance, or can it be optional and we remove [1], so that we can bump to controller-tools 0.14.0?

[1] https://github.com/openstack-k8s-operators/glance-operator/blob/main/api/v1beta1/glance_types.go#L110C5-L110C28

**Comment by stuggi** [comment]
This is the error:
```
  [FAILED] Unexpected error:
      <*fmt.wrapError | 0xc0001ba1a0>: 
      unable to install CRDs onto control plane: unable to create CRD instances: unable to create CRD "glances.glance.openstack.org": CustomResourceDefinition.apiextensions.k8s.io "glances.glance.openstack.org" is invalid: spec.validation.openAPIV3Schema.properties[spec].properties[imageCache].default.size: Required value
      {
          msg: "unable to install CRDs onto control plane: unable to create CRD instances: unable to create CRD \"glances.glance.openstack.org\": CustomResourceDefinition.apiextensions.k8s.io \"glances.glance.openstack.org\" is invalid: spec.validation.openAPIV3Schema.properties[spec].properties[imageCache].default.size: Required value",
          err: <*fmt.wrapError | 0xc0001ba180>{
              msg: "unable to create CRD instances: unable to create CRD \"glances.glance.openstack.org\": CustomResourceDefinition.apiextensions.k8s.io \"glances.glance.openstack.org\" is invalid: spec.validation.openAPIV3Schema.properties[spec].properties[imageCache].default.size: Required value",
              err: <*fmt.wrapError | 0xc0001ba160>{
                  msg: "unable to create CRD \"glances.glance.openstack.org\": CustomResourceDefinition.apiextensions.k8s.io \"glances.glance.openstack.org\" is invalid: spec.validation.openAPIV3Schema.properties[spec].properties[imageCache].default.size: Required value",
                  err: <*errors.StatusError | 0xc0003a2280>{
                      ErrStatus: {
                          TypeMeta: {Kind: "", APIVersion: ""},
                          ListMeta: {
                              SelfLink: "",
                              ResourceVersion: "",
                              Continue: "",
                              RemainingItemCount: nil,
                          },
                          Status: "Failure",
                          Message: "CustomResourceDefinition.apiextensions.k8s.io \"glances.glance.openstack.org\" is invalid: spec.validation.openAPIV3Schema.properties[spec].properties[imageCache].default.size: Required value",
                          Reason: "Invalid",
                          Details: {
                              Name: "glances.glance.openstack.org",
                              Group: "apiextensions.k8s.io",
                              Kind: "CustomResourceDefinition",
                              UID: "",
                              Causes: [
                                  {
                                      Type: "FieldValueRequired",
                                      Message: "Required value",
                                      Field: "spec.validation.openAPIV3Schema.properties[spec].properties[imageCache].default.size",
                                  },
                              ],
                              RetryAfterSeconds: 0,
                          },
                          Code: 422,
                      },
                  },
              },
          },
      }
  occurred
```
could be fixed by removing https://github.com/openstack-k8s-operators/glance-operator/blob/main/api/v1beta1/glance_types.go#L110C5-L110C28

**Comment by fmount** [comment]
> @fmount there is an issue with the glance crd which prevents bumping to controller tools 0.14.0. The `imageCache.size` is a required value. With controller-tools 0.14.0 support for empty maps/lists was introduced https://github.com/kubernetes-sigs/controller-tools/releases/tag/v0.14.0 . This now really applies the defaulting in [1] . Is the imageCache config a required config for glance, or can it be optional and we remove [1], so that we can bump to controller-tools 0.14.0?
> 
> [1] https://github.com/openstack-k8s-operators/glance-operator/blob/main/api/v1beta1/glance_types.go#L110C5-L110C28

`ImageCache` is not required at deployment time: customers can decide to enable this feature later in time (day2) and patch the Glance CR. So I agree this is not a required parameter and the API should be fixed to reflect that.
Thank you, I guess you can remove [1].

[1] https://github.com/openstack-k8s-operators/glance-operator/blob/main/api/v1beta1/glance_types.go#L110

**Comment by stuggi** [comment]
> > @fmount there is an issue with the glance crd which prevents bumping to controller tools 0.14.0. The `imageCache.size` is a required value. With controller-tools 0.14.0 support for empty maps/lists was introduced https://github.com/kubernetes-sigs/controller-tools/releases/tag/v0.14.0 . This now really applies the defaulting in [1] . Is the imageCache config a required config for glance, or can it be optional and we remove [1], so that we can bump to controller-tools 0.14.0?
> > [1] https://github.com/openstack-k8s-operators/glance-operator/blob/main/api/v1beta1/glance_types.go#L110C5-L110C28
> 
> `ImageCache` is not required at deployment time: customers can decide to enable this feature later in time (day2) and patch the Glance CR. So I agree this is not a required parameter and the API should be fixed to reflect that. Thank you, I guess you can remove [1].
> 
> [1] https://github.com/openstack-k8s-operators/glance-operator/blob/main/api/v1beta1/glance_types.go#L110

Ack, was guessing that, but first wanted to check with you. Thanks, will update the pr.

**Comment by stuggi** [comment]
> @stuggi seems good now and kuttl (which is supposed to validate imageCache) seems to work.

yes seems to be good. can you approve ?

**Review by fmount — APPROVED** [review]
/lgtm

**Pull request merged**
