### PR TITLE
Support disconnected network environments

### PR DESCRIPTION
**Pull request by dprince**
This PR adds support for installing the operator in disconnected network environments.

### CODE REVIEW

**Comment by dprince** [comment]
Re the failed CI here. It seems we run 'make bundle' before our operator builds complete in CI. This should resolve the issue: https://github.com/openshift/release/pull/4204

**Comment by fmount** [comment]
Still seems broken but unrelated to the patch [1]. Looks like oc fails to authenticate to the `api`: maybe we should debug more or pass the right `--certificate-authority` to the `oc` client?
/cc @viroel @Sandeepyadav93 

[1] https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_glance-operator/290/pull-ci-openstack-k8s-operators-glance-operator-main-glance-operator-build-deploy-tempest/1688905767928729600/artifacts/glance-operator-build-deploy-tempest/openstack-k8s-operators-build/build-log.txt

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
