### PR TITLE
Scale up glance_split & glance_image_cache api KUTTL test

### PR DESCRIPTION
**Pull request by vhariria**

### CODE REVIEW

**Comment by vhariria** [comment]
The failure error is are unrelated to the changes. Required further triage/retest.

**Comment by vhariria** [comment]
ci/prow/functional appears failure is unrelated to changes:
step src failed: could not resolve pipeline image stream tag root: imagestreamtags.image.openshift.io "pipeline:root" not found

**Review by fmount — APPROVED** [review]
/lgtm

**Pull request merged**
