### PR TITLE
consider global nodeSelector if not specified on the api level

### PR DESCRIPTION
**Pull request by stuggi**

### CODE REVIEW

**Review by fmount — APPROVED** [review]

**Comment by abays** [comment]
> @stuggi: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> Test name 	Commit 	Details 	Required 	Rerun command
> ci/prow/images 	[9387b9f](https://github.com/openstack-k8s-operators/glance-operator/commit/9387b9fd028e122e58ab273c84ecf7b52980cebb) 	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_glance-operator/272/pull-ci-openstack-k8s-operators-glance-operator-main-images/1679442596000174080) 	true 	`/test images`
> 
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=glance-operator&pr=272). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:stuggi).

I think this is caused by the Prow infrastructure issues that Sandeep mentioned.  We'll have to wait until they resolve before this can pass.

**Pull request merged**
