### PR TITLE
Enable ginkgolinter

### PR DESCRIPTION
**Pull request by bshewale**

### CODE REVIEW

**Comment by bshewale** [comment]
This PR is Depends-On: https://github.com/openshift/release/pull/38448

**Comment by abays** [comment]
> This PR is Depends-On: [openshift/release#38448](https://github.com/openshift/release/pull/38448)

@bshewale Please see the comment from @viroel here: https://github.com/openshift/release/pull/38448#discussion_r1172907987

**Comment by bshewale** [comment]
> ee the comment from @

hey @abays fixed the review comment thanks :)

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
