### PR TITLE
Fix a few copy-paste erorrs in Glance type

### PR DESCRIPTION
**Pull request by abays**

### CODE REVIEW

**Review by bogdando — APPROVED** [review]
LGTM :)

**Review by stuggi — COMMENTED** [review]
have you run make manifests? seems there are updates to the yamls missing?

**Comment by abays** [comment]
> have you run make manifests? seems there are updates to the yamls missing?

I am waiting for this PR: https://github.com/openstack-k8s-operators/glance-operator/pull/19 to merge.  Then perhaps we can merge another PR to trigger the generation/push of the images to quay...and then I will submit a patch for `install_yamls` to deploy Glance using those images.

**Comment by dprince** [comment]
@abays PR #19 is merged! want to rebase this and give it a shot?

**Comment by abays** [comment]
The failures here seem to be from the test suites/tools themselves, not the Glance operator code

**Pull request merged**
