### PR TITLE
Use common memcached.GetMemcachedServerListWithInetString()

### PR DESCRIPTION
**Pull request by stuggi**
Use common func to retrieve the memcached server list for a memcached instance.

### CODE REVIEW

**Comment by stuggi** [comment]
Warning  Failed          13m (x6 over 14m)     kubelet            Error: ImagePullBackOff
  Normal   Pulling         12m (x4 over 14m)     kubelet            Pulling image "quay.io/podified-antelope-centos9/openstack-memcached@sha256:8347d7e59d00117771cdc68c39c2ccebcfb6dbd197689bd2231a1e9fd8fb44c6"
  Warning  Failed          12m (x4 over 14m)     kubelet            Failed to pull image "quay.io/podified-antelope-centos9/openstack-memcached@sha256:8347d7e59d00117771cdc68c39c2ccebcfb6dbd197689bd2231a1e9fd8fb44c6": rpc error: code = Unknown desc = reading manifest sha256:8347d7e59d00117771cdc68c39c2ccebcfb6dbd197689bd2231a1e9fd8fb44c6 in quay.io/podified-antelope-centos9/openstack-memcached: manifest unknown

**Review by fmount — APPROVED** [review]
/lgtm

**Pull request merged**
