### PR TITLE
Add OWNERS file

### PR DESCRIPTION
**Pull request by viroel**
Adds a OWNERS file, needed for OpenShift-CI (Prow)

### CODE REVIEW

**Review by abays — APPROVED** [review]
Looks good for an initial pass.  If we need to add others we can do so in follow-ups.

/lgtm

**Review by stuggi — CHANGES_REQUESTED** [review]
please also add fmount, konan-abhi and fultonj

**Comment by viroel** [comment]
> please also add fmount, konan-abhi and fultonj

done.

**Review by stuggi — APPROVED** [review]
/lgtm thanks!

**Pull request merged**
