### PR TITLE
Update test helper references after reorg

### PR DESCRIPTION
**Pull request by gibizer**
Depends-On: openstack-k8s-operators/lib-common#301

### CODE REVIEW

**Review by stuggi — APPROVED** [review]
/lgtm

**Comment by stuggi** [comment]
I think it also needs a change here https://github.com/openstack-k8s-operators/glance-operator/blob/main/tests/functional/suite_test.go#L33

**Comment by gibizer** [comment]
> I think it also needs a change here https://github.com/openstack-k8s-operators/glance-operator/blob/main/tests/functional/suite_test.go#L33

you are right. It is strange that neither go mod tidy nor the build detected that we import a nonexistent module. Fixed now.

**Review by stuggi — APPROVED** [review]
/lgtm

**Pull request merged**
