### PR TITLE
Use central renovate config

### PR DESCRIPTION
**Pull request by fmount**
As done for other operators, this change switches renovate to a central config.

### CODE REVIEW

**Review by abays — APPROVED** [review]
/lgtm

**Comment by abays** [comment]
We'll need to rebase once https://github.com/openstack-k8s-operators/glance-operator/pull/274 is merged so we can pass KUTTL CI

**Comment by fmount** [comment]
> We'll need to rebase once #274 is merged so we can pass KUTTL CI

Done, let's see now the CI in action!

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
