### PR TITLE
Add glance-operator icon based on the Glance project logo

### PR DESCRIPTION
**Pull request by fmount**
Jira: https://issues.redhat.com/browse/OSPRH-8226

### CODE REVIEW

**Comment by fmount** [comment]
We previously had:

```
ERRO[0000] Error: Value : (glance-operator.v0.0.1) csv.Spec.Icon elements should contain both data and mediatype
```
and with a bundle built on top of this patch:

` operator-sdk bundle validate --select-optional name=operatorhub --optional-values=k8s-version=1.22 --verbose ./bundle` 

we don't have the same issue anymore.

**Review by konan-abhi — APPROVED** [review]

**Comment by abays** [comment]
Do we want to merge this?  The associated Jira doesn't seem to be a blocker.

**Comment by fmount** [comment]
> Do we want to merge this? The associated Jira doesn't seem to be a blocker.

Not a blocker IMO, now that operators deps are bumped I'm going to push the 18.0.0-proposed branch

**Comment by fmount** [comment]
> Do we want to merge this? The associated Jira doesn't seem to be a blocker.

FYI I kept this patch out of the 18.0.0-proposed branch

**Comment by abays** [comment]
> > Do we want to merge this? The associated Jira doesn't seem to be a blocker.
> 
> FYI I kept this patch out of the 18.0.0-proposed branch

Ah, right.  I forgot we have the branches now and can freely merge into `main`.  Doh. :-)

**Pull request merged**
