### PR TITLE
Mirror ReadyCondition with the actual current condition

### PR DESCRIPTION
**Pull request by fmount**
This patch covers two things:

- `Mirror()` relies on sorting conditions in each condition group by their `LastTransitionTime`, so it swaps the `RestoreLastTransitionTimes()` call with the `Mirror()` call in the defer function

- It setup `ReadyCondition` as `Unknown` instead of `False`, so we can avoid it to be the only one mirrored in the
  top-level status: this allows the other conditions to compete for the top-level mirroring

### CODE REVIEW

**Review by abays — APPROVED** [review]
/lgtm

**Review by ASBishop — APPROVED** [review]
/lgtm

I saw a demo of this and it works great. Until reconciliation completes, the ReadyCondition tells you which sub-condition isn't ready.

**Comment by ASBishop** [comment]
/retest

rabbitmq failure

**Pull request merged**
